FROM node:23-alpine

LABEL maintainer="Sam Laister <saml@everbit.dev>"

WORKDIR /usr/src/app

# Package JSON caching
COPY package.json ./
COPY package-lock.json ./

RUN npm ci

# Build
COPY . ./

RUN npm run build

EXPOSE 3000

CMD ["node", "build"]